### PR TITLE
refresh timepicker component when order type toggled

### PR DESCRIPTION
**Pull request by olieydt**
To fix issue [#348](https://github.com/tastyigniter/TastyIgniter/issues/348)

### CODE REVIEW

**Comment by olieydt** [comment]
I've added a check to make sure the localbox is present. Changing order types will affect the content of the timepicker, so something must be sent out from here. We could also fire an event from the cartbox and have the localbox listen and render the partial. What do you suggest?

**Comment by sampoyigi** [comment]
After my comment, I came across where I loaded the cartBox from the checkout component so let's continue with that approach but maybe add an option to specify the component alias when necessary using component properties. Something like, similar to what you've done

```
'cartBoxAlias' => [
     'label' => 'Specify the CartBox component alias used to refresh the cart after a payment is selected',
     'type' => 'text',
     'default' => 'cartBox',
],
```

```
if ($cartBox = $this->controller->findComponentByAlias($this->property('cartBoxAlias'))) {
    $result['#cart-totals'] = $cartBox->renderPartial('@totals');
}
```

**Comment by olieydt** [comment]
That sounds good, ive added the property in the above commit.

**Comment by sampoyigi** [comment]
Perfect 👍

**Comment by sampoyigi** [comment]
Merged

**Pull request closed without merging**
