### PR TITLE
Use lang pack date formats

### PR DESCRIPTION
**Pull request by ryanmitchell**
As part of https://github.com/tastyigniter/TastyIgniter/pull/605

### CODE REVIEW

**Comment by sampoyigi** [comment]
Looking at the changes here, I don't think you should use the `convert_php_to_moment_js_format` helper... converting `l, jS F Y \a\t h:i a` to `DD MMM \a\t HH:mm` will be a tricky and could have unexpected results... I'd say duplicate the lang string under `main` namespace for the components? ex. `main::lang.date_format..`

**Comment by ryanmitchell** [comment]
So for each component date string have a new lang pack entry? Isn’t that just the same problem moved to a different place - ie that there are so many date strings to update?

I’m happy to spend some time getting the helper function working ‘right’?

**Comment by sampoyigi** [comment]
No no, all of the component's date formats will be pulled from the `main::` language strings and for the backend from `admin::` (you can move them from the `system::` lang file to the admin lang file since we now have different formats for frontend and backend). So it's just duplicating the same lang strings from the system into main lang file

**Comment by ryanmitchell** [comment]
So front end uses moment format, and backend PHP? Or just different PHP for front end and back end>

**Comment by sampoyigi** [comment]
Exactly!

**Comment by sampoyigi** [comment]
Moment format for the frontend and PHP for backend.

**Comment by ryanmitchell** [comment]
Should be all done

**Comment by sampoyigi** [comment]
Yups, I'll merge all the PR later.. Thank you!

Also, I've put all the lang string in one place under the system namespace, didn't want to bother you again with the changes ;).

**Review by sampoyigi — APPROVED** [review]

**Comment by ryanmitchell** [comment]
Thats cool thanks 👍

**Pull request merged**
